### ISSUE TITLE
#如何实现按需引入

### ISSUE THREAD

**Issue by chongyangwang** [zhousg/erabbit-ui#1]
周老师您好  冒昧提一个issue 在腾讯课堂看过我们小兔仙的课程 
主要是由两个疑问 
1. 全量打包  执行如下命令 会报 xtxTabs 等jsx语法编译会不支持 请问您是如何解决的

```
    "lib": "vue-cli-service build --target lib --name eribbit --dest lib packages/index.js"

```

如下
![image](https://user-images.githubusercontent.com/32251099/158357456-b47b65db-517a-4d38-b4a4-951184713a7b.png)

这是我的解决方案
![image](https://user-images.githubusercontent.com/32251099/158357580-6bac48b0-def1-473a-9428-f05b11ec84ca.png)

![image](https://user-images.githubusercontent.com/32251099/158358369-6638f00f-9b4b-4d95-8321-eef0592b83a1.png)

还想问下 如何实现erabbit-ui的非全量打包 能否给学生讲解下思路

**Comment by zhousg** [comment]
问题1：新版vuecli打包没问题
问题2：https://juejin.cn/post/6844904158181474311

这个库推上来主要上课使用，没时间维护。如果你有兴趣可以提提PR

**Comment by chongyangwang** [comment]
@zhousg  验证了下，确实是版本的问题，
昨天初始打包确实会报vue-loader语法问题 ，
![image](https://user-images.githubusercontent.com/32251099/158501895-a678c91f-4b4e-44b4-b67e-3ff379820885.png)

然后尝试切换了node和npm版本 ，无效后才加了那个配置，
 
重新安装依赖 并没有删掉那个配置   早上按您说的 把配置删了 竟然又好使了
